Repository earlybird-ticket/backend, pull requests merged in 2025-04, with the labels that each got.

#2 [ET-1] feat(common): common 모듈 구현 #1
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  common/build.gradle
  common/gradle/wrapper/gradle-wrapper.jar
  common/gradle/wrapper/gradle-wrapper.properties
  common/src/main/java/com/earlybirdticket/common/aop/AsyncConfig.java
  common/src/main/java/com/earlybirdticket/common/aop/CachingMdcFilter.java
  common/src/main/java/com/earlybirdticket/common/aop/LoggingAop.java
  common/src/main/java/com/earlybirdticket/common/aop/LoggingStatus.java
  common/src/main/java/com/earlybirdticket/common/aop/LoggingStatusManager.java
  common/src/main/java/com/earlybirdticket/common/aop/LoggingTracer.java
  common/src/main/java/com/earlybirdticket/common/aop/MdcTaskDecorator.java
  common/src/main/java/com/earlybirdticket/common/aop/WebLogConfig.java
  common/src/main/java/com/earlybirdticket/common/configuration/JpaConfig.java
  common/src/main/java/com/earlybirdticket/common/configuration/QueryDslConfig.java
  common/src/main/java/com/earlybirdticket/common/entity/BaseEntity.java
  common/src/main/java/com/earlybirdticket/common/entity/CommonDto.java
  common/src/main/java/com/earlybirdticket/common/entity/EventPayload.java
  common/src/main/java/com/earlybirdticket/common/entity/Outbox.java
  common/src/main/java/com/earlybirdticket/common/entity/OutboxRepository.java
  common/src/main/java/com/earlybirdticket/common/entity/PassportDto.java
  common/src/main/java/com/earlybirdticket/common/entity/constant/ErrorCode.java
  common/src/main/java/com/earlybirdticket/common/entity/constant/EventType.java
  common/src/main/java/com/earlybirdticket/common/entity/constant/Role.java
  common/src/main/java/com/earlybirdticket/common/exception/BadRequestFeignExceptionHandler.java
  common/src/main/java/com/earlybirdticket/common/exception/FeignExceptionHandlerStrategy.java
  common/src/main/java/com/earlybirdticket/common/exception/GlobalExceptionHandler.java
  common/src/main/java/com/earlybirdticket/common/exception/NotFoundFeignExceptionHandler.java
  common/src/main/java/com/earlybirdticket/common/exception/ServerErrorFeignExceptionHandler.java
  common/src/main/java/com/earlybirdticket/common/util/CommonUtil.java
  common/src/main/java/com/earlybirdticket/common/util/DataUtil.java
  common/src/main/java/com/earlybirdticket/common/util/DateParserUtil.java
  common/src/main/java/com/earlybirdticket/common/util/EventPayloadConverter.java
  common/src/main/java/com/earlybirdticket/common/util/MDCTraceUtils.java
  common/src/main/java/com/earlybirdticket/common/util/PageUtil.java
  common/src/main/java/com/earlybirdticket/common/util/PassportUtil.java
  common/src/main/java/com/earlybirdticket/common/util/QueryUtil.java
  common/src/main/resources/META-INF/spring.factories
Labels: enhancement

#8 [ET-15] chore(auth) : 모듈 생성
  auth/.gitattributes
  auth/.gitignore
  auth/build.gradle
  auth/gradle/wrapper/gradle-wrapper.jar
  auth/gradle/wrapper/gradle-wrapper.properties
  auth/gradlew
  auth/gradlew.bat
  auth/settings.gradle
  auth/src/main/java/com/earlybirdticket/auth/AuthApplication.java
  auth/src/main/resources/application.yml
  settings.gradle
Labels: chore

#10 [EV-4] chore(eureka) : Eureka 서버 구현
  server/.gitattributes
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/earlybirdticket/server/ServerApplication.java
  server/src/main/resources/application.yml
Labels: chore

#6 [ET-14] Payment 모듈 추가
  payment/.gitattributes
  payment/.gitignore
  payment/build.gradle
  payment/gradle/wrapper/gradle-wrapper.jar
  payment/gradle/wrapper/gradle-wrapper.properties
  payment/gradlew
  payment/gradlew.bat
  payment/settings.gradle
  payment/src/main/java/com/earlybird/ticket/PaymentApplication.java
  payment/src/main/java/com/earlybird/ticket/application/service/PaymentEventProducer.java
  payment/src/main/java/com/earlybird/ticket/application/service/PaymentService.java
  payment/src/main/java/com/earlybird/ticket/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/earlybird/ticket/common/CommonConfig.java
  payment/src/main/java/com/earlybird/ticket/domain/entity/Payment.java
  payment/src/main/java/com/earlybird/ticket/domain/repository/PaymentRepository.java
  payment/src/main/java/com/earlybird/ticket/infrastructure/config/KafkaConfig.java
  payment/src/main/java/com/earlybird/ticket/infrastructure/messaging/PaymentKafkaEventListener.java
  payment/src/main/java/com/earlybird/ticket/infrastructure/messaging/PaymentKafkaEventProducer.java
  payment/src/main/java/com/earlybird/ticket/infrastructure/repository/PaymentJpaRepository.java
  payment/src/main/java/com/earlybird/ticket/infrastructure/repository/PaymentRepositoryImpl.java
  payment/src/main/java/com/earlybird/ticket/presentation/PaymentController.java
  payment/src/main/resources/application.yml
  settings.gradle
Labels: chore

#4 [ET-13] chore(venue) : venue 모듈 세팅 (#3)
  settings.gradle
  venue/.gitattributes
  venue/.gitignore
  venue/build.gradle
  venue/gradle/wrapper/gradle-wrapper.jar
  venue/gradle/wrapper/gradle-wrapper.properties
  venue/gradlew
  venue/gradlew.bat
  venue/settings.gradle
  venue/src/main/java/com/earlybird/ticket/venue/VenueApplication.java
  venue/src/test/java/com/earlybird/ticket/venue/VenueApplicationTests.java
Labels: chore

#14 [ET-16] feat(Auth) : 환경 설정
  auth/src/main/java/com/earlybird/ticket/auth/AuthApplication.java
  auth/src/main/java/com/earlybird/ticket/auth/application/AuthService.java
  auth/src/main/java/com/earlybird/ticket/auth/application/AuthServiceImpl.java
  auth/src/main/java/com/earlybird/ticket/auth/application/UserClient.java
  auth/src/main/java/com/earlybird/ticket/auth/infrastructure/client/UserClientImpl.java
  auth/src/main/java/com/earlybird/ticket/auth/infrastructure/client/UserFeignClient.java
  auth/src/main/java/com/earlybird/ticket/auth/presentation/AuthExternalController.java
Labels: enhancement

#18 [ET-7] feat(common): admin 모듈 구현 #17
  admin/build.gradle
  admin/gradle/wrapper/gradle-wrapper.jar
  admin/gradle/wrapper/gradle-wrapper.properties
  admin/src/main/java/com/earlybird/ticket/admin/AdminApplication.java
  admin/src/main/java/com/earlybird/ticket/admin/infrastructure/config/CommonConfig.java
  admin/src/main/resources/application.yml
  admin/src/test/java/com/earlybird/ticket/admin/AdminApplicationTests.java
  settings.gradle
Labels: enhancement

#19 [ET-2] chore: docker 환경 설정 #16
  Dockerfile
  docker-compose.db.yml
  docker-compose.log.yml
  docker-compose.monitoring.yml
Labels: chore

#20 [ET-18] chore(gateway) : gateway 모듈 추가
  gateway/.gitattributes
  gateway/.gitignore
  gateway/build.gradle
  gateway/gradle/wrapper/gradle-wrapper.jar
  gateway/gradle/wrapper/gradle-wrapper.properties
  gateway/src/main/java/com/earlybird/ticket/gateway/GatewayApplication.java
  gateway/src/main/java/com/earlybird/ticket/gateway/infrastructure/config/SecurityWebConfig.java
  gateway/src/main/resources/application.yml
  settings.gradle
Labels: chore

#22 [ET-22] feat(coupon): coupon 모듈 구현 #21
  .github/pull_request_template.md
  coupon/build.gradle
  coupon/gradle/wrapper/gradle-wrapper.jar
  coupon/gradle/wrapper/gradle-wrapper.properties
  coupon/src/main/java/com/earlybird/ticket/coupon/CouponApplication.java
  coupon/src/main/java/com/earlybird/ticket/coupon/infrastructure/config/CommonConfig.java
  coupon/src/main/resources/application.yml
  coupon/src/test/java/com/earlybird/ticket/coupon/CouponApplicationTests.java
  settings.gradle
Labels: enhancement

#25 Feat(common)/code,role
  common/src/main/java/com/earlybird/ticket/common/entity/CommonDto.java
  common/src/main/java/com/earlybird/ticket/common/entity/constant/Code.java
  common/src/main/java/com/earlybird/ticket/common/entity/constant/Role.java
  common/src/main/java/com/earlybird/ticket/common/exception/BadRequestFeignExceptionHandler.java
  common/src/main/java/com/earlybird/ticket/common/exception/NotFoundFeignExceptionHandler.java
  common/src/main/java/com/earlybird/ticket/common/exception/ServerErrorFeignExceptionHandler.java
Labels: enhancement

#27 [ET-19], [ET-24] TokenValidator 추가 및 common 모듈 import 충돌 해결
  gateway/build.gradle
  gateway/src/main/java/com/earlybird/ticket/gateway/GatewayApplication.java
  gateway/src/main/java/com/earlybird/ticket/gateway/domain/TokenStatus.java
  gateway/src/main/java/com/earlybird/ticket/gateway/infrastructure/TokenValidator.java
  gateway/src/main/resources/application.yml
Labels: enhancement

#30 [ET-25] feat(Auth) : 일반 회원, 판매자 회원 가입 구현
  auth/build.gradle
  auth/settings.gradle
  auth/src/main/java/com/earlybird/ticket/auth/application/AuthService.java
  auth/src/main/java/com/earlybird/ticket/auth/application/AuthServiceImpl.java
  auth/src/main/java/com/earlybird/ticket/auth/application/UserClient.java
  auth/src/main/java/com/earlybird/ticket/auth/application/dto/commander/CreateSellerCommand.java
  auth/src/main/java/com/earlybird/ticket/auth/application/dto/commander/CreateUserCommand.java
  auth/src/main/java/com/earlybird/ticket/auth/infrastructure/client/UserClientImpl.java
  auth/src/main/java/com/earlybird/ticket/auth/infrastructure/config/FeignConfig.java
  auth/src/main/java/com/earlybird/ticket/auth/presentation/AuthExternalController.java
  auth/src/main/java/com/earlybird/ticket/auth/presentation/dto/request/CreateSellerRequest.java
  auth/src/main/java/com/earlybird/ticket/auth/presentation/dto/request/CreateUserRequest.java
  auth/src/main/resources/application.yml
Labels: enhancement

#29 [ET-20] JWT 인증 필터 추가
  gateway/src/main/java/com/earlybird/ticket/gateway/infrastructure/config/SecurityWebConfig.java
  gateway/src/main/java/com/earlybird/ticket/gateway/infrastructure/security/JwtAuthenticationManager.java
  gateway/src/main/java/com/earlybird/ticket/gateway/infrastructure/security/JwtServerAuthenticationConverter.java
  gateway/src/main/java/com/earlybird/ticket/gateway/infrastructure/security/filter/AddPassportHeaderGatewayFilter.java
Labels: enhancement

#32 [ET-30] chore(user) : 유저 모듈 추가
  settings.gradle
  user/.gitattributes
  user/.gitignore
  user/build.gradle
  user/gradle/wrapper/gradle-wrapper.jar
  user/gradle/wrapper/gradle-wrapper.properties
  user/src/main/java/com/earlybird/ticket/user/UserApplication.java
  user/src/main/java/com/earlybird/ticket/user/application/service/UserService.java
  user/src/main/java/com/earlybird/ticket/user/application/service/UserServiceImpl.java
  user/src/main/java/com/earlybird/ticket/user/domain/entity/User.java
  user/src/main/java/com/earlybird/ticket/user/domain/repository/UserRepository.java
  user/src/main/java/com/earlybird/ticket/user/infrastructure/config/CommonConfig.java
  user/src/main/java/com/earlybird/ticket/user/infrastructure/repository/UserJpaRepository.java
  user/src/main/java/com/earlybird/ticket/user/infrastructure/repository/UserRepositoryImpl.java
  user/src/main/java/com/earlybird/ticket/user/presentation/ExternalUserController.java
  user/src/main/java/com/earlybird/ticket/user/presentation/InternalUserController.java
  user/src/main/resources/application.yml
Labels: chore

#34 Feat(venue)/set package
  venue/settings.gradle
  venue/src/main/java/com/earlybird/ticket/venue/VenueApplication.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/Event.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/EventType.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dispatcher/EventDispatcher.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dispatcher/EventDispatcherImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/VenueCreatePayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/response/SeatPreemptSuccessEvent.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/EventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/VenueCreateEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatService.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/VenueService.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/VenueServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/common/CommonConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/Hall.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/Seat.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/SeatInstant.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/Venue.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/constant/Grade.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/constant/Status.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/repository/SeatRepository.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/repository/VenueRepository.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/kafka/KafkaConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/kafka/KafkaConsumerConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/kafka/KafkaProducerConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/messaging/SeatKafkaEventListener.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/messaging/SeatKafkaOutboxProducer.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/messaging/VenueKafkaEventListener.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/messaging/VenueKafkaOutboxProducer.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/SeatJpaRepository.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/SeatQueryRepository.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/SeatQueryRepositoryImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/SeatRepositoryImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/VenueJpaRepository.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/VenueRepositoryImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/presentation/controller/SeatController.java
  venue/src/test/java/com/earlybird/ticket/venue/VenueApplicationTests.java
Labels: enhancement

#42 [ET- 34] feat(common) : logback-spring 추가
  common/src/main/resources/logback-spring.xml
Labels: enhancement

#40 [ET-33] fix(common) : 공통 모듈 수정
  common/src/main/java/com/earlybird/ticket/common/entity/CommonDto.java
  common/src/main/java/com/earlybird/ticket/common/exception/BadRequestFeignExceptionHandler.java
  common/src/main/java/com/earlybird/ticket/common/exception/NotFoundFeignExceptionHandler.java
  common/src/main/java/com/earlybird/ticket/common/exception/ServerErrorFeignExceptionHandler.java
Labels: refactor

#45 [ET-36] 사용자 이메일 검증 기능 추가
  user/src/main/java/com/earlybird/ticket/user/application/dto/command/ProcessUserEmailValidateCommand.java
  user/src/main/java/com/earlybird/ticket/user/application/exception/AbstractUserException.java
  user/src/main/java/com/earlybird/ticket/user/application/exception/UserEmailDuplicatedException.java
  user/src/main/java/com/earlybird/ticket/user/application/service/UserService.java
  user/src/main/java/com/earlybird/ticket/user/application/service/UserServiceImpl.java
  user/src/main/java/com/earlybird/ticket/user/domain/constant/Grade.java
  user/src/main/java/com/earlybird/ticket/user/domain/entity/User.java
  user/src/main/java/com/earlybird/ticket/user/domain/repository/UserRepository.java
  user/src/main/java/com/earlybird/ticket/user/infrastructure/config/CommonConfig.java
  user/src/main/java/com/earlybird/ticket/user/infrastructure/repository/UserJpaRepository.java
  user/src/main/java/com/earlybird/ticket/user/infrastructure/repository/UserRepositoryImpl.java
  user/src/main/java/com/earlybird/ticket/user/presentation/ExternalUserController.java
  user/src/main/java/com/earlybird/ticket/user/presentation/dto/request/FindUserEmailRequest.java
Labels: enhancement

#48 [ET-38] feat(auth) : 회원 탈퇴 구현
  auth/src/main/java/com/earlybird/ticket/auth/application/AuthService.java
  auth/src/main/java/com/earlybird/ticket/auth/application/AuthServiceImpl.java
  auth/src/main/java/com/earlybird/ticket/auth/application/ReservationClient.java
  auth/src/main/java/com/earlybird/ticket/auth/application/UserClient.java
  auth/src/main/java/com/earlybird/ticket/auth/common/config/CommonConfig.java
  auth/src/main/java/com/earlybird/ticket/auth/common/config/SecurityConfig.java
  auth/src/main/java/com/earlybird/ticket/auth/common/exception/ReservationExistException.java
  auth/src/main/java/com/earlybird/ticket/auth/infrastructure/client/ReservationFeignClient.java
  auth/src/main/java/com/earlybird/ticket/auth/infrastructure/client/ReservationFeignImpl.java
  auth/src/main/java/com/earlybird/ticket/auth/infrastructure/client/UserClientImpl.java
  auth/src/main/java/com/earlybird/ticket/auth/infrastructure/client/UserFeignClient.java
  auth/src/main/java/com/earlybird/ticket/auth/presentation/AuthExternalController.java
Labels: enhancement

#51 [ET-37], [ET-39] (일반 회원/판매자) 회원 가입 기능 구현
  common/src/main/java/com/earlybird/ticket/common/entity/BaseEntity.java
  user/src/main/java/com/earlybird/ticket/user/application/dto/command/CreateUserCustomerCommand.java
  user/src/main/java/com/earlybird/ticket/user/application/dto/command/CreateUserSellerCommand.java
  user/src/main/java/com/earlybird/ticket/user/application/service/UserService.java
  user/src/main/java/com/earlybird/ticket/user/application/service/UserServiceImpl.java
  user/src/main/java/com/earlybird/ticket/user/domain/entity/Seller.java
  user/src/main/java/com/earlybird/ticket/user/domain/entity/User.java
  user/src/main/java/com/earlybird/ticket/user/domain/repository/UserRepository.java
  user/src/main/java/com/earlybird/ticket/user/infrastructure/repository/UserRepositoryImpl.java
  user/src/main/java/com/earlybird/ticket/user/presentation/InternalUserController.java
  user/src/main/java/com/earlybird/ticket/user/presentation/dto/request/SignUpUserCustomerRequest.java
  user/src/main/java/com/earlybird/ticket/user/presentation/dto/request/SignUpUserSellerRequest.java
  user/src/main/resources/application.yml
Labels: bug, enhancement

#58 [ET-51] Refactor(auth)/segregate join dto
  auth/src/main/java/com/earlybird/ticket/auth/application/UserClient.java
  auth/src/main/java/com/earlybird/ticket/auth/application/dto/commander/GetUserIdPasswordRoleCommand.java
  auth/src/main/java/com/earlybird/ticket/auth/application/dto/commander/JoinUserCommand.java
  auth/src/main/java/com/earlybird/ticket/auth/infrastructure/client/UserClientImpl.java
  auth/src/main/java/com/earlybird/ticket/auth/infrastructure/client/UserFeignClient.java
Labels: refactor

#59 Feat(user)/implement user search
  user/src/main/java/com/earlybird/ticket/user/application/dto/query/FindUserQuery.java
  user/src/main/java/com/earlybird/ticket/user/application/dto/query/GetUserIdPasswordRoleQuery.java
  user/src/main/java/com/earlybird/ticket/user/application/exception/UserNotFoundException.java
  user/src/main/java/com/earlybird/ticket/user/application/service/UserService.java
  user/src/main/java/com/earlybird/ticket/user/application/service/UserServiceImpl.java
  user/src/main/java/com/earlybird/ticket/user/domain/entity/Seller.java
  user/src/main/java/com/earlybird/ticket/user/domain/repository/UserRepository.java
  user/src/main/java/com/earlybird/ticket/user/infrastructure/config/CommonConfig.java
  user/src/main/java/com/earlybird/ticket/user/infrastructure/repository/UserJpaRepository.java
  user/src/main/java/com/earlybird/ticket/user/infrastructure/repository/UserRepositoryImpl.java
  user/src/main/java/com/earlybird/ticket/user/presentation/ExternalUserController.java
  user/src/main/java/com/earlybird/ticket/user/presentation/InternalUserController.java
  user/src/main/java/com/earlybird/ticket/user/presentation/dto/request/FindUserEmailDuplicatedRequest.java
  user/src/main/java/com/earlybird/ticket/user/presentation/dto/request/FindUserEmailRequest.java
  user/src/main/java/com/earlybird/ticket/user/presentation/dto/request/SignUpUserSellerRequest.java
  user/src/main/java/com/earlybird/ticket/user/presentation/dto/response/FindUserInfoResponse.java
  user/src/main/java/com/earlybird/ticket/user/presentation/dto/response/GetUserEmailPasswordRoleResponse.java
Labels: enhancement

#63 [ET-50] feat(common) : AuditAware 구현체 추가
  common/src/main/java/com/earlybird/ticket/common/configuration/HeaderAuditAwareImpl.java
Labels: enhancement

#65 [ET-52] rename(user) : 필드명 birthDate -> birthDay로 일괄 수정
  user/src/main/java/com/earlybird/ticket/user/application/dto/command/CreateUserCustomerCommand.java
  user/src/main/java/com/earlybird/ticket/user/application/dto/command/CreateUserSellerCommand.java
  user/src/main/java/com/earlybird/ticket/user/application/dto/query/FindUserQuery.java
  user/src/main/java/com/earlybird/ticket/user/domain/entity/User.java
  user/src/main/java/com/earlybird/ticket/user/presentation/dto/response/FindUserInfoResponse.java
Labels: refactor

#62 Chore(reservation)/setting
  reservation/build.gradle
  reservation/src/main/java/com/earlybird/ticket/reservation/ReservationApplication.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/ReservationService.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/ReservationServiceImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/kafka/config/KafkaConfig.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/kafka/config/KafkaConsumerConfig.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/kafka/config/KafkaProducerConfig.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/kafka/producer/KafkaProducerInterceptor.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/kafka/producer/KafkaProducerListener.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/redis/config/RedisConfig.java
  reservation/src/main/java/com/earlybird/ticket/reservation/presentation/ReservationExternalController.java
  reservation/src/main/resources/application.yml
  settings.gradle
Labels: chore

#67 [ET-40] refactor(auth) : User와 birthDay field 이름 일치하도록 수정, yml수정
  auth/build.gradle
  auth/src/main/java/com/earlybird/ticket/auth/application/AuthServiceImpl.java
  auth/src/main/java/com/earlybird/ticket/auth/application/UserClient.java
  auth/src/main/java/com/earlybird/ticket/auth/application/dto/commander/CreateSellerCommand.java
  auth/src/main/java/com/earlybird/ticket/auth/application/dto/commander/CreateUserCommand.java
  auth/src/main/java/com/earlybird/ticket/auth/infrastructure/client/UserClientImpl.java
  auth/src/main/java/com/earlybird/ticket/auth/presentation/dto/request/CreateSellerRequest.java
  auth/src/main/java/com/earlybird/ticket/auth/presentation/dto/request/CreateUserRequest.java
  auth/src/main/resources/application.yml
Labels: bug, refactor

#70 Feat(seat)/find seat
  venue/src/main/java/com/earlybird/ticket/venue/application/dto/response/SeatListQuery.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatService.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/dto/SeatListResult.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/repository/SeatRepository.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/SeatQueryRepository.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/SeatQueryRepositoryImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/SeatRepositoryImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/presentation/controller/SeatController.java
  venue/src/main/java/com/earlybird/ticket/venue/presentation/dto/response/SeatListResponse.java
Labels: enhancement

#71 [ET-44] feat(user) : 회원정보 수정 기능 추가[비밀번호 제외]
  user/src/main/java/com/earlybird/ticket/user/application/dto/command/UpdateUserCustomerCommand.java
  user/src/main/java/com/earlybird/ticket/user/application/service/UserService.java
  user/src/main/java/com/earlybird/ticket/user/application/service/UserServiceImpl.java
  user/src/main/java/com/earlybird/ticket/user/domain/entity/User.java
  user/src/main/java/com/earlybird/ticket/user/presentation/ExternalUserController.java
  user/src/main/java/com/earlybird/ticket/user/presentation/dto/request/UpdateUserCustomerRequest.java
Labels: enhancement

#75 [ET-56] 회원 비밀번호 수정 기능 추가
  user/src/main/java/com/earlybird/ticket/user/application/dto/command/UpdateUserCustomerPasswordCommand.java
  user/src/main/java/com/earlybird/ticket/user/application/service/UserService.java
  user/src/main/java/com/earlybird/ticket/user/application/service/UserServiceImpl.java
  user/src/main/java/com/earlybird/ticket/user/domain/entity/User.java
  user/src/main/java/com/earlybird/ticket/user/presentation/InternalUserController.java
  user/src/main/java/com/earlybird/ticket/user/presentation/dto/request/UpdateUserCustomerPasswordRequest.java
Labels: enhancement

#79 [EV-42] feat(reservation) : 환경설정
  reservation/src/main/java/com/earlybird/ticket/reservation/application/ReservationService.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/ReservationServiceImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/dto/CreateReservationCommand.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/service/ReservationServiceImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/Outbox.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/Reservation.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/ReservationSeat.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/constant/ConcertStatus.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/constant/CouponStatus.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/constant/CouponType.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/constant/PaymentMethod.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/constant/ReservationStatus.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/constant/SeatGrade.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/constant/SeatStatus.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/repository/OutboxRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/repository/ReservationRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/repository/ReservationSeatRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/messaging/config/KafkaConfig.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/messaging/config/KafkaConsumerConfig.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/messaging/config/KafkaProducerConfig.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/messaging/producer/KafkaProducerInterceptor.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/messaging/producer/KafkaProducerListener.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/outbox/OutboxJpaRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/outbox/OutboxRepositoryImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservation/ReservationJpaRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservation/ReservationQueryDslRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservation/ReservationQueryDslRepositoryImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservation/ReservationRepositoryImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservationSeat/ReservationSeatJpaRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservationSeat/ReservationSeatRepositoryImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/presentation/ReservationExternalController.java
  reservation/src/main/java/com/earlybird/ticket/reservation/presentation/dto/request/CreateReservationRequest.java
  reservation/src/main/java/com/earlybird/ticket/reservation/presentation/dto/response/FindReservationQuery.java
  reservation/src/main/resources/application.yml
Labels: enhancement

#78 [ET-45] feat(user) : 회원 탈퇴 기능 구현
  user/src/main/java/com/earlybird/ticket/user/application/service/UserService.java
  user/src/main/java/com/earlybird/ticket/user/application/service/UserServiceImpl.java
  user/src/main/java/com/earlybird/ticket/user/domain/repository/UserRepository.java
  user/src/main/java/com/earlybird/ticket/user/presentation/InternalUserController.java
Labels: enhancement

#81 [ET-28], [ET-54] Gateway 수정
  gateway/src/main/java/com/earlybird/ticket/gateway/infrastructure/config/SecurityWebConfig.java
  gateway/src/main/java/com/earlybird/ticket/gateway/infrastructure/security/JwtServerAuthenticationConverter.java
  gateway/src/main/java/com/earlybird/ticket/gateway/infrastructure/security/filter/AddPassportHeaderGatewayFilter.java
  gateway/src/main/resources/application.yml
Labels: refactor, fix

#82 Feat(venue/seat)/set kafka
  venue/.gitignore
  venue/src/main/java/com/earlybird/ticket/venue/application/dto/request/ProcessSeatCheckCommand.java
  venue/src/main/java/com/earlybird/ticket/venue/application/dto/response/ProcessSeatCheckQuery.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/Event.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/EventType.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/SeatConfirmPayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/SeatCreatePayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/SeatInstanceCreatePayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/SeatInstanceDeletePayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/SeatInstanceUpdatePayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/SeatPreemptPayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/SeatReturnPayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/VenueDeletePayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/VenueUpdatePayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/response/SeatConfirmFailEvent.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/response/SeatConfirmSuccessEvent.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/response/SeatPreemptFailEvent.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/response/SeatReturnFailEvent.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/response/SeatReturnSuccessEvent.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatConfirmEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatCreateEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatInstanceCreateEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatInstanceDeleteEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatInstanceUpdateEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatPreemptEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatReturnEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/VenueCreateEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/VenueDeleteEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/VenueUpdateEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatService.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/VenueService.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/VenueServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/common/config/CommonConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/Hall.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/Outbox.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/Seat.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/kafka/KafkaConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/kafka/KafkaConsumerConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/kafka/KafkaProducerConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/kafka/KafkaProducerInterceptor.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/kafka/KafkaProducerListener.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/messaging/SeatKafkaEventListener.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/messaging/SeatKafkaOutboxProducer.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/messaging/VenueKafkaEventListener.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/OutboxRepository.java
  venue/src/main/java/com/earlybird/ticket/venue/presentation/dto/request/ProcessSeatCheckRequest.java
  venue/src/main/java/com/earlybird/ticket/venue/presentation/dto/response/ProcessSeatCheckResponse.java
Labels: chore

#86 Feat(seat)/check seat
  venue/src/main/java/com/earlybird/ticket/venue/application/dto/response/ProcessSeatCheckQuery.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/VenueCreateEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/common/exception/SeatNotFoundException.java
  venue/src/main/java/com/earlybird/ticket/venue/common/exception/SeatUnavailableException.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/Seat.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/SeatInstant.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/repository/SeatRepository.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/messaging/VenueKafkaEventListener.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/SeatQueryRepository.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/SeatQueryRepositoryImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/SeatRepositoryImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/presentation/controller/SeatController.java
Labels: enhancement

#88 [ET-61] fix(user) : InternalUserController 문법 오류 수정
  user/src/main/java/com/earlybird/ticket/user/presentation/InternalUserController.java
Labels: fix

#96 [ET-63] feat(admin): admin entity 구현 #91
  admin/src/main/java/com/earlybird/ticket/admin/domain/entity/Admin.java
Labels: enhancement

#97 [ET-64] chore(admin): Admin Service Kafka Config #92
  admin/build.gradle
  admin/src/main/java/com/earlybird/ticket/admin/infrastructure/config/CommonConfig.java
  admin/src/main/java/com/earlybird/ticket/admin/infrastructure/config/KafkaConsumerConfig.java
  admin/src/main/java/com/earlybird/ticket/admin/infrastructure/config/KafkaProducerConfig.java
  admin/src/main/resources/application.yml
Labels: chore

#99 [ET-65] feat(admin): Admin Repository 구현 #93
  admin/src/main/java/com/earlybird/ticket/admin/domain/AdminRepository.java
  admin/src/main/java/com/earlybird/ticket/admin/infrastructure/repository/AdminJpaRepository.java
  admin/src/main/java/com/earlybird/ticket/admin/infrastructure/repository/AdminQueryDslRepository.java
  admin/src/main/java/com/earlybird/ticket/admin/infrastructure/repository/AdminQueryDslRepositoryImpl.java
  admin/src/main/java/com/earlybird/ticket/admin/infrastructure/repository/AdminRepositoryImpl.java
Labels: enhancement

#98 [ET-62] feat(admin): Admin Service Outbox 구현 #90
  .gitignore
  admin/src/main/java/com/earlybird/ticket/admin/common/AggregateType.java
  admin/src/main/java/com/earlybird/ticket/admin/common/Outbox.java
  admin/src/main/java/com/earlybird/ticket/admin/common/OutboxRepository.java
  admin/src/main/java/com/earlybird/ticket/admin/infrastructure/event/OutboxPublisher.java
Labels: enhancement

#104 [ET-66] feat(admin): RegisterSeatCommand 추가 #94
  .gitignore
  admin/src/main/java/com/earlybird/ticket/admin/application/AdminService.java
  admin/src/main/java/com/earlybird/ticket/admin/application/AdminServiceImpl.java
  admin/src/main/java/com/earlybird/ticket/admin/application/dto/DeleteSeatCommand.java
  admin/src/main/java/com/earlybird/ticket/admin/application/dto/RegisterSeatCommand.java
  admin/src/main/java/com/earlybird/ticket/admin/application/dto/UpdateSeatCommand.java
Labels: enhancement

#101 [ET-67] feat(admin): Admin Controller 구현 #95
  admin/src/main/java/com/earlybird/ticket/admin/presentation/AdminController.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/DeleteCouponRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/DeleteSeatRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/DeleteVenueRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/RegisterCouponIssueRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/RegisterVenueRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/UpdateCouponRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/UpdateSeatRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/UpdateVenueRequest.java
Labels: enhancement

#106 Feat(seat)/update delete seat instance
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/SeatInstanceDeletePayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/SeatInstanceUpdatePayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/Seat.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/SeatInstance.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/repository/SeatRepository.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/SeatQueryRepository.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/SeatQueryRepositoryImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/SeatRepositoryImpl.java
Labels: enhancement

#113 Feat(venue)/create venue
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/VenueDeletePayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/VenueUpdatePayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/VenueServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/common/exception/VenueCreateException.java
  venue/src/main/java/com/earlybird/ticket/venue/common/exception/VenueNotFoundException.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/Hall.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/Venue.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/repository/VenueRepository.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/VenueRepositoryImpl.java
Labels: enhancement

#120 [ET-77] fix(gateway) : 게이트웨이 화이트리스트 수정
  gateway/src/main/java/com/earlybird/ticket/gateway/infrastructure/security/filter/AddPassportHeaderGatewayFilter.java
Labels: bug

#118 [ET-76] refactor(reservation) : 각 계층 리팩토링
  reservation/src/main/java/com/earlybird/ticket/reservation/application/dto/CreateReservationCommand.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/service/ReservationServiceImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/messaging/producer/ReservationKafkaOutboxProducer.java
  reservation/src/main/java/com/earlybird/ticket/reservation/presentation/ReservationExternalController.java
  reservation/src/main/java/com/earlybird/ticket/reservation/presentation/dto/request/CreateReservationRequest.java
Labels: enhancement

#116 [ET-75] feat(reservation) : 좌석 선점 응답(성공/실패) 컨슈밍
  reservation/src/main/java/com/earlybird/ticket/reservation/application/dispatcher/EventDispatcher.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/dispatcher/EventDispatcherImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/dto/response/SeatPreemptFailEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/dto/response/SeatPreemptSuccessEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/SeatReserveFailEventHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/SeatReserveSuccessEventHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/service/ReservationServiceImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/common/exception/NotFoundReservationException.java
  reservation/src/main/java/com/earlybird/ticket/reservation/common/exception/SeatAlreadyReservedException.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/ConfirmSeatPayload.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/CouponConfirmPayload.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/CouponReservePayload.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/CouponReturnPayload.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/PreemptSeatPayload.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/ReturnSeatPayload.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/Reservation.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/ReservationSeat.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/constant/EventType.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/repository/ReservationRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/repository/ReservationSeatRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/messaging/consumer/ReservationKafkaEventListener.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservation/ReservationRepositoryImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservationSeat/ReservationSeatJpaRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservationSeat/ReservationSeatRepositoryImpl.java
Labels: enhancement

#124 Feat(venue)/set consumer handler
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/response/SeatConfirmFailEvent.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/response/SeatPreemptFailEvent.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/response/SeatReturnFailEvent.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatConfirmEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatCreateEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatHandlerService.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatHandlerServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatInstanceCreateEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatInstanceDeleteEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatInstanceUpdateEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatPreemptEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatReturnEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/VenueCreateEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/VenueDeleteEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/VenueHandlerService.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/VenueHandlerServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/VenueUpdateEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatService.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/common/event/EventType.java
  venue/src/main/java/com/earlybird/ticket/venue/common/exception/JsonDeserializationException.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/Event.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/constant/Status.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/messaging/SeatKafkaEventListener.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/messaging/VenueKafkaEventListener.java
Labels: enhancement

#127 [ET-78] feat(admin): Admin Event Produce 구현 #121
  admin/build.gradle
  admin/src/main/java/com/earlybird/ticket/admin/application/event/Event.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/EventType.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/CouponCreatePayload.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/CouponDeletePayload.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/CouponIssuePayload.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/CouponUpdatePayload.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/SeatCreatePayload.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/SeatInstanceDeletePayload.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/SeatInstanceUpdatePayload.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/VenueCreatePayload.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/VenueDeletePayload.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/VenueUpdatePayload.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/handler/EventHandler.java
  admin/src/main/java/com/earlybird/ticket/admin/common/AggregateType.java
  admin/src/main/java/com/earlybird/ticket/admin/common/Outbox.java
  admin/src/main/java/com/earlybird/ticket/admin/infrastructure/config/KafkaProducerConfig.java
  admin/src/main/java/com/earlybird/ticket/admin/infrastructure/event/OutboxPublisher.java
  admin/src/main/resources/application.yml
Labels: enhancement

#131 [ET-83] feat(admin): Admin Controller API 구현 #130
  admin/src/main/java/com/earlybird/ticket/admin/presentation/AdminController.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/controller/AdminController.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/DeleteCouponRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/DeleteSeatInstanceRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/DeleteSeatRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/DeleteVenueRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/RegisterCouponIssueRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/RegisterCouponRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/RegisterSeatRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/RegisterVenueRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/UpdateCouponRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/UpdateSeatInstanceRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/UpdateSeatRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/UpdateVenueRequest.java
Labels: enhancement

#129 Feat(seat)/produce fail message
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/response/SeatConfirmSuccessEvent.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/response/SeatPreemptSuccessEvent.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/response/SeatReturnSuccessEvent.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatHandlerServiceImpl.java
Labels: enhancement

#134 [ET-84] 결제 엔티티 + 리포지토리 추가
  payment/src/main/java/com/earlybird/ticket/payment/common/CommonConfig.java
  payment/src/main/java/com/earlybird/ticket/payment/domain/entity/Payment.java
  payment/src/main/java/com/earlybird/ticket/payment/domain/entity/constant/PaymentMethod.java
  payment/src/main/java/com/earlybird/ticket/payment/domain/entity/constant/PaymentStatus.java
  payment/src/main/java/com/earlybird/ticket/payment/domain/repository/PaymentRepository.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/repository/PaymentRepositoryImpl.java
  payment/src/main/resources/application.yml
Labels: enhancement

#132 Refactor(seat)/refactor dto
  common/src/main/java/com/earlybird/ticket/common/entity/constant/Code.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/VenueCreatePayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatHandlerServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/VenueHandlerServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/Seat.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/Venue.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/dto/HallCreatResult.java
Labels: refactor

#139 [ET-87] fix(gateway) : payments, auth 경로에 대해 인증하지 않도록 수정
  gateway/src/main/java/com/earlybird/ticket/gateway/infrastructure/config/SecurityWebConfig.java
  gateway/src/main/java/com/earlybird/ticket/gateway/infrastructure/security/filter/AddPassportHeaderGatewayFilter.java
  payment/src/main/java/com/earlybird/ticket/payment/presentation/PaymentExternalController.java
Labels: fix

#137 [ET-85] feat(payment) : 결제 페이지 템플릿 추가
  payment/build.gradle
  payment/src/main/java/com/earlybird/ticket/payment/domain/entity/Payment.java
  payment/src/main/java/com/earlybird/ticket/payment/presentation/PaymentController.java
  payment/src/main/java/com/earlybird/ticket/payment/presentation/PaymentViewController.java
  payment/src/main/resources/application.yml
  payment/src/main/resources/templates/checkout.html
  payment/src/main/resources/templates/fail.html
  payment/src/main/resources/templates/success.html
Labels: enhancement

#141 [ET-88] feat(admin): Admin Outbox 이벤트 발행 구현 #140
  admin/src/main/java/com/earlybird/ticket/admin/application/AdminService.java
  admin/src/main/java/com/earlybird/ticket/admin/application/AdminServiceImpl.java
  admin/src/main/java/com/earlybird/ticket/admin/application/dto/RegisterVenueCommand.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/EventType.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/CouponCreateEvent.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/CouponDeleteEvent.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/CouponIssueEvent.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/CouponUpdateEvent.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/SeatCreateEvent.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/SeatInstanceDeleteEvent.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/SeatInstanceDeletePayload.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/SeatInstanceUpdateEvent.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/SeatInstanceUpdatePayload.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/VenueCreateEvent.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/VenueCreatePayload.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/VenueDeleteEvent.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/VenueDeletePayload.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/VenueUpdateEvent.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/dto/VenueUpdatePayload.java
  admin/src/main/java/com/earlybird/ticket/admin/common/Outbox.java
  admin/src/main/java/com/earlybird/ticket/admin/infrastructure/config/KafkaProducerConfig.java
  admin/src/main/java/com/earlybird/ticket/admin/infrastructure/config/KafkaProducerInterceptor.java
  admin/src/main/java/com/earlybird/ticket/admin/infrastructure/config/KafkaProducerListener.java
  admin/src/main/java/com/earlybird/ticket/admin/infrastructure/event/OutboxPublisher.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/DeleteSeatInstanceRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/DeleteVenueRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/RegisterVenueRequest.java
  admin/src/main/java/com/earlybird/ticket/admin/presentation/dto/UpdateVenueRequest.java
  http/Admin.http
Labels: enhancement

#144 [ET-90] feat(concert): concert 모듈 구현 #143
  concert/build.gradle
  concert/src/main/java/com/earlybird/ticket/concert/ConcertApplication.java
  concert/src/main/java/com/earlybird/ticket/concert/infrastructure/CommonConfig.java
  concert/src/main/resources/application.yml
  concert/src/test/java/com/earlybird/ticket/concert/ConcertApplicationTests.java
  settings.gradle
Labels: enhancement

#151 [ET-97] fix(gateway) : payment 하위 경로 인가 처리하지 않도록 수정
  gateway/src/main/java/com/earlybird/ticket/gateway/infrastructure/security/filter/AddPassportHeaderGatewayFilter.java
Labels: enhancement

#152 [ET-86] refactor(reservation) : 예약 생성 기능 리팩토링
  reservation/src/main/java/com/earlybird/ticket/reservation/application/dto/CreateReservationCommand.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/service/ReservationServiceImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/repository/ReservationSeatRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/messaging/config/KafkaConsumerConfig.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/messaging/config/KafkaProducerConfig.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservationSeat/ReservationSeatRepositoryImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/presentation/ReservationExternalController.java
  reservation/src/main/java/com/earlybird/ticket/reservation/presentation/dto/request/CreateReservationRequest.java
  reservation/src/main/resources/application.yml
Labels: enhancement, refactor

#154 [ET-91] feat(concert): concert entity 구현 #153
  concert/src/main/java/com/earlybird/ticket/concert/domain/Concert.java
  concert/src/main/java/com/earlybird/ticket/concert/domain/ConcertSequence.java
  concert/src/main/java/com/earlybird/ticket/concert/domain/SeatInstanceInfo.java
  concert/src/main/java/com/earlybird/ticket/concert/domain/constant/ConcertStatus.java
  concert/src/main/java/com/earlybird/ticket/concert/domain/constant/Genre.java
Labels: enhancement

#156 [ET-100] feat(reservation) : 좌석 조회 기능 구현
  reservation/src/main/java/com/earlybird/ticket/reservation/application/dto/response/FindReservationQuery.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/service/ReservationServiceImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/repository/ReservationSeatRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservationSeat/ReservationSeatJpaRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservationSeat/ReservationSeatRepositoryImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/presentation/EventTestController.java
  reservation/src/main/java/com/earlybird/ticket/reservation/presentation/ReservationExternalController.java
  reservation/src/main/java/com/earlybird/ticket/reservation/presentation/dto/response/FindReservationResponse.java
Labels: enhancement

#160 [ET-101] feat(reservation) : 예약 검색 기능 구현
  reservation/src/main/java/com/earlybird/ticket/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/service/ReservationServiceImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/response/ReservationSearchResult.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/repository/ReservationSeatRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservation/ReservationQueryDslRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservation/ReservationQueryDslRepositoryImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservationSeat/ReservationSeatRepositoryImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/presentation/ReservationExternalController.java
Labels: enhancement

#159 [ET-99] TossPay 응답값 가공 후 결제 내역 반영
  payment/src/main/java/com/earlybird/ticket/payment/application/service/PaymentClient.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/dto/command/ConfirmPaymentCommand.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/dto/command/CreatePaymentCommand.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/dto/command/UpdatePaymentCommand.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/dto/query/FindPaymentQuery.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/exception/PaymentAbortException.java
  payment/src/main/java/com/earlybird/ticket/payment/domain/entity/Payment.java
  payment/src/main/java/com/earlybird/ticket/payment/domain/entity/constant/PaymentMethod.java
  payment/src/main/java/com/earlybird/ticket/payment/domain/entity/constant/PaymentStatus.java
  payment/src/main/java/com/earlybird/ticket/payment/domain/repository/PaymentRepository.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/client/PaymentWebClient.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/client/dto/response/ConfirmPaymentMethodClientResponse.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/repository/PaymentJpaRepository.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/repository/PaymentRepositoryImpl.java
  payment/src/main/java/com/earlybird/ticket/payment/presentation/PaymentExternalController.java
  payment/src/main/java/com/earlybird/ticket/payment/presentation/dto/request/ConfirmPaymentRequest.java
  payment/src/main/java/com/earlybird/ticket/payment/presentation/dto/request/CreatePaymentRequest.java
  payment/src/main/java/com/earlybird/ticket/payment/presentation/dto/request/FindPaymentResponse.java
  payment/src/main/java/com/earlybird/ticket/payment/presentation/dto/response/GetPaymentIdResponse.java
  payment/src/main/resources/templates/checkout.html
Labels: enhancement

#162 Refactor(seat)/refactor kafka logic
  venue/src/main/java/com/earlybird/ticket/venue/VenueApplication.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatConfirmEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatHandlerServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/common/event/util/EventConverter.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/Seat.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/Venue.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/constant/Status.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/kafka/KafkaConsumerConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/kafka/KafkaProducerConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/messaging/SeatKafkaEventListener.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/messaging/VenueKafkaOutboxProducer.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/SeatQueryRepositoryImpl.java
Labels: refactor

#164 [ET-99]Outbox 패턴 적용 + 관련 이벤트 생성
  payment/src/main/java/com/earlybird/ticket/PaymentApplication.java
  payment/src/main/java/com/earlybird/ticket/payment/application/event/dto/request/PaymentSuccessEvent.java
  payment/src/main/java/com/earlybird/ticket/payment/application/event/dto/response/PaymentFailEvent.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/exception/JsonDeserializationException.java
  payment/src/main/java/com/earlybird/ticket/payment/common/EventConverter.java
  payment/src/main/java/com/earlybird/ticket/payment/common/EventType.java
  payment/src/main/java/com/earlybird/ticket/payment/domain/entity/Event.java
  payment/src/main/java/com/earlybird/ticket/payment/domain/entity/Outbox.java
  payment/src/main/java/com/earlybird/ticket/payment/domain/repository/OutboxRepository.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/messaging/PaymentKafkaEventProducer.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/messaging/PaymentKafkaOutboxProducer.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/repository/OutboxJpaRepository.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/repository/OutboxRepositoryImpl.java
Labels: enhancement

#169 [ET-106] feat(reservation) : 결제 성공 이벤트 Consuming 및 쿠폰 , 좌석 확정 이벤트 발행
  reservation/src/main/java/com/earlybird/ticket/reservation/application/dto/response/CouponReservePayload.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/dto/response/PaymentSuccessPayload.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ReserveCouponPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ReservePaymentSuccessPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ReserveSeatFailEventHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ReserveSeatSuccessEventHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/common/util/EventPayloadConverter.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/ConfirmCouponEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/ConfirmSeatEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/FailCouponEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/ReserveCouponEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/ReserveCouponPayload.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/ReturnCouponPayload.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/Event.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/Reservation.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/constant/EventType.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/messaging/config/KafkaConfig.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/messaging/consumer/ReservationKafkaEventListener.java
Labels: enhancement

#170 [ET-104], [ET-105] Feat(payment)/implement producing event
  payment/src/main/java/com/earlybird/ticket/payment/application/event/dto/request/PaymentFailEvent.java
  payment/src/main/java/com/earlybird/ticket/payment/application/event/dto/request/PaymentSuccessEvent.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/earlybird/ticket/payment/common/EventType.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/config/KafkaConfig.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/config/KafkaProducerConfig.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/config/KafkaProducerInterceptor.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/config/KafkaProducerListener.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/messaging/PaymentKafkaOutboxProducer.java
  payment/src/main/resources/application.yml
Labels: enhancement

#175 [ET-108] refactor(reservation) : 좌석 선점/확정/반환 성공 및 실패 이벤트 처리 구현
  reservation/src/main/java/com/earlybird/ticket/reservation/application/dto/response/SeatConfirmFailPayload.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/dto/response/SeatConfirmSuccessPayload.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/dto/response/SeatReturnFailPayload.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/dto/response/SeatReturnSuccessPayload.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ConfirmSeatFailPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ConfirmSeatSuccessPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/PreemptSeatFailPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/PreemptSeatSuccessPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ReturnSeatFailPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ReturnSeatSuccessPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/ReservationSeat.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/constant/EventType.java
Labels: enhancement

#179 [ET-93] feat(concert): Concert Service 구현 #178
  concert/src/main/java/com/earlybird/ticket/concert/application/ConcertService.java
  concert/src/main/java/com/earlybird/ticket/concert/application/ConcertServiceImpl.java
  concert/src/main/java/com/earlybird/ticket/concert/application/dto/DeleteConcertCommand.java
  concert/src/main/java/com/earlybird/ticket/concert/application/dto/DeleteConcertSequenceCommand.java
  concert/src/main/java/com/earlybird/ticket/concert/application/dto/ProcessConcertDetailsCommand.java
  concert/src/main/java/com/earlybird/ticket/concert/application/dto/ProcessConcertDetailsQuery.java
  concert/src/main/java/com/earlybird/ticket/concert/application/dto/ProcessConcertQuery.java
  concert/src/main/java/com/earlybird/ticket/concert/application/dto/ProcessConcertsCommand.java
  concert/src/main/java/com/earlybird/ticket/concert/application/dto/RegisterConcertCommand.java
  concert/src/main/java/com/earlybird/ticket/concert/application/dto/UpdateConcertCommand.java
  concert/src/main/java/com/earlybird/ticket/concert/application/dto/UpdateConcertSequenceCommand.java
  concert/src/main/java/com/earlybird/ticket/concert/domain/Concert.java
  concert/src/main/java/com/earlybird/ticket/concert/domain/ConcertSequence.java
  concert/src/main/java/com/earlybird/ticket/concert/domain/SeatInstanceInfo.java
  concert/src/main/java/com/earlybird/ticket/concert/domain/constant/Grade.java
  concert/src/main/java/com/earlybird/ticket/concert/domain/constant/Section.java
Labels: enhancement

#188 Feat(seat)/set redis
  venue/build.gradle
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatHandlerServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/common/exception/TimeOutException.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/kafka/KafkaConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/kafka/KafkaConsumerConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/redis/RedisConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/messaging/SeatKafkaEventListener.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/messaging/VenueKafkaEventListener.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/messaging/VenueKafkaOutboxProducer.java
Labels: enhancement

#181 [ET-98] feat(concert): Concert Outbox 구현 #180
  concert/build.gradle
  concert/src/main/java/com/earlybird/ticket/concert/application/event/Event.java
  concert/src/main/java/com/earlybird/ticket/concert/application/event/EventType.java
  concert/src/main/java/com/earlybird/ticket/concert/application/event/dto/ConcertCreateSuccessEvent.java
  concert/src/main/java/com/earlybird/ticket/concert/common/Outbox.java
  concert/src/main/java/com/earlybird/ticket/concert/common/OutboxRepository.java
  concert/src/main/java/com/earlybird/ticket/concert/infrastructure/KafkaProducerConfig.java
  concert/src/main/java/com/earlybird/ticket/concert/infrastructure/event/OutboxPublisher.java
  concert/src/main/resources/application.yml
Labels: enhancement

#183 [ET-94] feat(concert): Concert Controller 구현 #182
  concert/src/main/java/com/earlybird/ticket/concert/presentation/ConcertController.java
  concert/src/main/java/com/earlybird/ticket/concert/presentation/dto/DeleteConcertRequest.java
  concert/src/main/java/com/earlybird/ticket/concert/presentation/dto/DeleteConcertSequenceRequest.java
  concert/src/main/java/com/earlybird/ticket/concert/presentation/dto/ProcessConcertDetailsRequest.java
  concert/src/main/java/com/earlybird/ticket/concert/presentation/dto/ProcessConcertRequest.java
  concert/src/main/java/com/earlybird/ticket/concert/presentation/dto/RegisterConcertRequest.java
  concert/src/main/java/com/earlybird/ticket/concert/presentation/dto/UpdateConcertRequest.java
  concert/src/main/java/com/earlybird/ticket/concert/presentation/dto/UpdateConcertSequenceRequest.java
  http/Concert.http
Labels: enhancement

#185 [ET-110] 예약 타임아웃 체크
  common/src/main/java/com/earlybird/ticket/common/entity/constant/Code.java
  payment/build.gradle
  payment/src/main/java/com/earlybird/ticket/payment/application/TemporaryStore.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/PaymentEventProducer.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/exception/PaymentTimeoutException.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/cache/PaymentRedisTemporaryStore.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/client/PaymentWebClient.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/messaging/PaymentKafkaOutboxProducer.java
  payment/src/main/java/com/earlybird/ticket/payment/presentation/PaymentExternalController.java
  payment/src/main/resources/application.yml
Labels: enhancement

#191 [ET-116], [ET-117] Payment 리팩토링
  payment/src/main/java/com/earlybird/ticket/payment/application/service/PaymentService.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/exception/PaymentTimeoutException.java
  payment/src/main/java/com/earlybird/ticket/payment/domain/repository/OutboxRepository.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/cache/PaymentRedisTemporaryStore.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/config/KafkaConfig.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/config/RedissonConfig.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/messaging/PaymentKafkaOutboxProducer.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/repository/OutboxRepositoryImpl.java
Labels: refactor

#192 Feat(seat)/set cache
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/SeatConfirmPayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/SeatPreemptPayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatHandlerServiceImpl.java
Labels: enhancement

#198 Refactor(seat)/refactor seat instance
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatHandlerServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/messaging/SeatKafkaEventListener.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/messaging/VenueKafkaEventListener.java
Labels: refactor

#201 Refactor(seat)/refactor convention
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatConfirmEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatReturnEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/common/event/EventType.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/kafka/KafkaConfig.java
Labels: refactor

#205 [ET-125],[ET-126] refactor: event convention 적용 #204
  admin/src/main/java/com/earlybird/ticket/admin/application/AdminServiceImpl.java
  admin/src/main/java/com/earlybird/ticket/admin/application/event/EventType.java
  concert/src/main/java/com/earlybird/ticket/concert/application/ConcertServiceImpl.java
  concert/src/main/java/com/earlybird/ticket/concert/application/event/EventType.java
  concert/src/main/java/com/earlybird/ticket/concert/application/event/dto/ConcertCreateSuccessEvent.java
Labels: refactor

#207 Refactor(venue)/refactor kafka port
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/kafka/KafkaConsumerConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/kafka/KafkaProducerConfig.java
Labels: refactor

#209 [ET-128] refactor(payment) : 카프카 브로커 변수로 변경 + Outbox 정리
  \
  common/src/main/java/com/earlybird/ticket/common/entity/Outbox.java
  common/src/main/java/com/earlybird/ticket/common/entity/OutboxRepository.java
  common/src/main/java/com/earlybird/ticket/common/util/EventPayloadConverter.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/config/KafkaProducerConfig.java
  payment/src/main/resources/application.yml
Labels: enhancement

#216 [ET-132] feat(concert): concert entity 변경사항 적용 #215
  concert/src/main/java/com/earlybird/ticket/concert/application/dto/RegisterConcertCommand.java
  concert/src/main/java/com/earlybird/ticket/concert/application/event/dto/ConcertCreateSuccessEvent.java
  concert/src/main/java/com/earlybird/ticket/concert/domain/Concert.java
  concert/src/main/java/com/earlybird/ticket/concert/domain/ConcertSequence.java
  concert/src/main/java/com/earlybird/ticket/concert/presentation/dto/RegisterConcertRequest.java
Labels: enhancement

#217 [ET-132] feat(concert): concert entity 변경사항 적용 #215
  concert/src/main/java/com/earlybird/ticket/concert/application/event/dto/ConcertCreateSuccessEvent.java
Labels: enhancement

#222 Chore(venue)/set yml
  venue/.gitignore
  venue/src/main/resources/application.yml
Labels: chore

#224 [ET-139] test(payment) : 테스트 결제 서비스 수정
  payment/src/main/java/com/earlybird/ticket/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/TestPaymentServiceImpl.java
  payment/src/main/resources/application.yml
Labels: fix

#226 [ET-140] yml service 이름 수정 및 gateway macos silicon 의존성 추가
  admin/src/main/resources/application.yml
  concert/src/main/resources/application.yml
  gateway/build.gradle
  venue/src/main/resources/application.yml
Labels: chore

#228 [ET-141] refactor(venue) : 동일한 필드가 들어간 create 메서드 hallId로 수정
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatHandlerServiceImpl.java
Labels: refactor

#230 [ET-134] feat(coupon): coupon repository 구현 #229
  coupon/src/main/java/com/earlybird/ticket/coupon/domain/CouponRepository.java
  coupon/src/main/java/com/earlybird/ticket/coupon/domain/dto/CouponResult.java
  coupon/src/main/java/com/earlybird/ticket/coupon/domain/dto/UserCouponResult.java
  coupon/src/main/java/com/earlybird/ticket/coupon/infrastructure/repository/CouponJpaRepository.java
  coupon/src/main/java/com/earlybird/ticket/coupon/infrastructure/repository/CouponQueryDslRepository.java
  coupon/src/main/java/com/earlybird/ticket/coupon/infrastructure/repository/CouponQueryDslRepositoryImpl.java
  coupon/src/main/java/com/earlybird/ticket/coupon/infrastructure/repository/CouponRepositoryImpl.java
Labels: enhancement

#232 [ET-142] refactor(all) : Event 필드명 eventType으로 일괄 수정
  admin/src/main/java/com/earlybird/ticket/admin/application/event/Event.java
  admin/src/main/resources/application.yml
  concert/src/main/java/com/earlybird/ticket/concert/application/event/Event.java
  concert/src/main/resources/application.yml
  reservation/src/main/resources/application.yml
Labels: fix

#234 [ET-143] fix(reservation) : 좌석IdList로 통일
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ReservePaymentSuccessPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/service/ReservationServiceImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/ConfirmSeatEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/PreemptSeatDltEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/PreemptSeatEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/ReturnSeatEvent.java
Labels: bug

#236 [ET-144] feat(concert): concert 조회 기능 구현 #235
  concert/gradle/wrapper/gradle-wrapper.jar
  concert/gradle/wrapper/gradle-wrapper.properties
  concert/src/main/java/com/earlybird/ticket/concert/application/ConcertService.java
  concert/src/main/java/com/earlybird/ticket/concert/application/ConcertServiceImpl.java
  concert/src/main/java/com/earlybird/ticket/concert/application/dto/ProcessConcertDetailsQuery.java
  concert/src/main/java/com/earlybird/ticket/concert/application/dto/ProcessConcertQuery.java
  concert/src/main/java/com/earlybird/ticket/concert/domain/ConcertRepository.java
  concert/src/main/java/com/earlybird/ticket/concert/infrastructure/repository/ConcertQueryDslRepository.java
  concert/src/main/java/com/earlybird/ticket/concert/infrastructure/repository/ConcertQueryDslRepositoryImpl.java
  concert/src/main/java/com/earlybird/ticket/concert/infrastructure/repository/ConcertRepositoryImpl.java
  concert/src/main/java/com/earlybird/ticket/concert/presentation/ConcertController.java
  concert/src/main/java/com/earlybird/ticket/concert/presentation/dto/ProcessConcertDetailsRequest.java
  concert/src/main/java/com/earlybird/ticket/concert/presentation/dto/ProcessConcertDetailsResponse.java
  concert/src/main/java/com/earlybird/ticket/concert/presentation/dto/ProcessConcertRequest.java
  concert/src/main/java/com/earlybird/ticket/concert/presentation/dto/ProcessConcertResponse.java
  http/Concert.http
Labels: enhancement

#238 [ET108] feat(payment) : 결제 취소 API 연동
  payment/src/main/java/com/earlybird/ticket/payment/application/service/PaymentClient.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/TestPaymentServiceImpl.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/dto/command/UpdatePaymentCancelCommand.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/exception/PaymentCancelException.java
  payment/src/main/java/com/earlybird/ticket/payment/domain/entity/Payment.java
  payment/src/main/java/com/earlybird/ticket/payment/domain/entity/constant/PaymentStatus.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/client/PaymentWebClient.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/client/dto/response/ProcessPaymentCancelClientResponse.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/client/dto/response/ProcessPaymentConfirmClientResponse.java
  payment/src/main/java/com/earlybird/ticket/payment/presentation/PaymentExternalController.java
Labels: enhancement

#242 [ET-147] fix(payment) : 이벤트 직렬화 문제 수정
  payment/src/main/java/com/earlybird/ticket/payment/common/EventConverter.java
  payment/src/main/resources/application.yml
Labels: fix

#246 [ET-148] refactor(coupon): coupon repository 메서드 수정 #245
  coupon/src/main/java/com/earlybird/ticket/coupon/domain/CouponRepository.java
  coupon/src/main/java/com/earlybird/ticket/coupon/domain/dto/CouponResult.java
  coupon/src/main/java/com/earlybird/ticket/coupon/domain/dto/UserCouponResult.java
  coupon/src/main/java/com/earlybird/ticket/coupon/domain/dto/UserCouponResults.java
  coupon/src/main/java/com/earlybird/ticket/coupon/infrastructure/repository/CouponQueryDslRepository.java
  coupon/src/main/java/com/earlybird/ticket/coupon/infrastructure/repository/CouponQueryDslRepositoryImpl.java
  coupon/src/main/java/com/earlybird/ticket/coupon/infrastructure/repository/CouponRepositoryImpl.java
Labels: refactor

#240 [ET-145] refactor(concert): toEntity 메서드 내 엔티티를 분리하여 저장하도록 수정 #239
  concert/src/main/java/com/earlybird/ticket/concert/application/dto/RegisterConcertCommand.java
  concert/src/main/java/com/earlybird/ticket/concert/domain/Concert.java
Labels: refactor

#244 [ET-146] refactor(admin) : StringSerializer로 변경 (#243)
  admin/src/main/java/com/earlybird/ticket/admin/infrastructure/config/KafkaProducerConfig.java
Labels: refactor

#248 [ET-137] feat(coupon): coupon event handler 구현 #247
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/Event.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/EventDispatcher.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/EventDispatcherImpl.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/EventType.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/dto/CouponConfirmPayload.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/dto/CouponCreatePayload.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/dto/CouponDeletePayload.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/dto/CouponReserveEvent.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/dto/CouponReservePayload.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/dto/CouponUpdatePayload.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/dto/ReturnCouponEvent.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/dto/ReturnCouponPayload.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/dto/SuccessCouponPayload.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/handler/CouponConfirmEventHandler.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/handler/CouponCreateEventHandler.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/handler/CouponDeleteEventHandler.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/handler/CouponFailEventHandler.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/handler/CouponReturnEventHandler.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/handler/CouponSuccessEventHandler.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/handler/CouponUpdateEventHandler.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/handler/EventHandler.java
Labels: enhancement

#253 [ET-150] feat(coupon): outbox 구현 #251
  coupon/src/main/java/com/earlybird/ticket/coupon/common/Outbox.java
  coupon/src/main/java/com/earlybird/ticket/coupon/common/OutboxRepository.java
Labels: enhancement

#254 [ET-135] feat(coupon): service 구현 #252
  coupon/src/main/java/com/earlybird/ticket/coupon/application/dto/ProcessCouponQuery.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/dto/ProcessCouponReserveCommand.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/dto/ProcessUserCouponQuery.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/service/CouponService.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/service/CouponServiceImpl.java
Labels: enhancement

#250 Refactor(venue)/refactor consumer config
  venue/src/main/java/com/earlybird/ticket/venue/common/event/util/EventConverter.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/kafka/KafkaConsumerConfig.java
Labels: refactor

#258 Bug(reservation/payment)/refactor bug
  payment/src/main/java/com/earlybird/ticket/payment/application/service/TestPaymentServiceImpl.java
  payment/src/main/java/com/earlybird/ticket/payment/domain/entity/constant/PaymentMethod.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/dto/response/SeatConfirmFailPayload.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ConfirmSeatFailPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ReservePaymentSuccessPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/common/util/EventPayloadConverter.java
Labels: bug

#256 [ET-136] feat(coupon): service 구현 #255
  coupon/src/main/java/com/earlybird/ticket/coupon/presentation/controller/CouponController.java
  coupon/src/main/java/com/earlybird/ticket/coupon/presentation/dto/ProcessCouponReserveRequest.java
  coupon/src/main/java/com/earlybird/ticket/coupon/presentation/dto/ProcessCouponResponse.java
  coupon/src/main/java/com/earlybird/ticket/coupon/presentation/dto/ProcessUserCouponResponse.java
  http/Coupon.http
Labels: enhancement

#259 [ET-152] refactor(concert) : concert 회차 정보 엔티티 생성 로직 수정, 발행시 직렬화 Stri…
  concert/src/main/java/com/earlybird/ticket/concert/domain/Concert.java
  concert/src/main/java/com/earlybird/ticket/concert/infrastructure/KafkaProducerConfig.java
Labels: refactor

#262 [ET-153] refactor(coupon) :handle메서드의 payload필드 passportDto에 맞춤
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/handler/CouponConfirmEventHandler.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/handler/CouponCreateEventHandler.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/handler/CouponDeleteEventHandler.java
  coupon/src/main/java/com/earlybird/ticket/coupon/application/event/handler/CouponUpdateEventHandler.java
Labels: refactor

#264 Refactor(seat)/remove check ttl
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatHandlerServiceImpl.java
Labels: refactor

#268 [ET-156] fix(payment) : 예약 시간 검증 로직 수정
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/cache/PaymentRedisTemporaryStore.java
Labels: fix

#275 [ET-159] refactor(reservation) : 예약 확정시 예약좌석 상태 수정
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ConfirmSeatSuccessPayloadHandler.java
Labels: refactor

#277 [ET-160] refactor(reservation) : 예약 상태에 따른 reservation, reservationSe…
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ConfirmSeatFailPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ConfirmSeatSuccessPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/PreemptSeatFailPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/PreemptSeatSuccessPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ReservePaymentSuccessPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ReturnSeatFailPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ReturnSeatSuccessPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/service/ReservationServiceImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/common/exception/LockFailedException.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/Reservation.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/ReservationSeat.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/messaging/producer/ReservationKafkaOutboxProducer.java
  reservation/src/main/resources/application.yml
Labels: refactor

#278 [ET-157] refactor(payment) : 결제 내역 검증 및 캐싱
  payment/src/main/java/com/earlybird/ticket/payment/application/TemporaryStore.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/TestPaymentServiceImpl.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/exception/PaymentDuplicatedException.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/cache/PaymentRedisTemporaryStore.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/client/PaymentWebClient.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/messaging/PaymentKafkaOutboxProducer.java
Labels: refactor

#280 [ET-108] 결제 취소 이벤트 방식으로 변경
  payment/src/main/java/com/earlybird/ticket/payment/application/event/dispatcher/EventDispatcher.java
  payment/src/main/java/com/earlybird/ticket/payment/application/event/dispatcher/EventDispatcherImpl.java
  payment/src/main/java/com/earlybird/ticket/payment/application/event/dto/response/ReservationCancelPayload.java
  payment/src/main/java/com/earlybird/ticket/payment/application/event/handler/EventHandler.java
  payment/src/main/java/com/earlybird/ticket/payment/application/event/handler/ReservationCancelPayloadHandler.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/PaymentService.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/PaymentServiceImpl.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/TestPaymentServiceImpl.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/dto/command/UpdatePaymentCommand.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/exception/PaymentInformationDoesNotMatchException.java
  payment/src/main/java/com/earlybird/ticket/payment/application/service/exception/PaymentNonRecoverableException.java
  payment/src/main/java/com/earlybird/ticket/payment/common/EventType.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/client/PaymentWebClient.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/client/dto/response/ProcessPaymentConfirmClientResponse.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/config/KafkaConsumerConfig.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/messaging/PaymentKafkaEventListener.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/messaging/consumer/PaymentKafkaEventListener.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/messaging/producer/KafkaProducerInterceptor.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/messaging/producer/KafkaProducerListener.java
  payment/src/main/java/com/earlybird/ticket/payment/infrastructure/messaging/producer/PaymentKafkaOutboxProducer.java
  payment/src/main/java/com/earlybird/ticket/payment/presentation/PaymentExternalController.java
  payment/src/main/resources/application.yml
Labels: enhancement

#283 [ET-162] feat(batch): batch 모듈 구현 #282
  batch/.gitattributes
  batch/.gitignore
  batch/build.gradle
  batch/gradlew
  batch/gradlew.bat
  batch/settings.gradle
  batch/src/main/java/com/earlybird/ticket/batch/BatchApplication.java
  batch/src/main/java/com/earlybird/ticket/batch/config/MetaDBConfig.java
  batch/src/main/resources/application.yml
  settings.gradle
Labels: enhancement

#285 [ET-167] chore(batch) : 각 서비스 DB 연결 정보 추가
  batch/build.gradle
  batch/src/main/java/com/earlybird/ticket/batch/config/sink/MetaDBConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/config/sink/SinkDBConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/config/source/AdminDBConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/config/source/ConcertDBConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/config/source/CouponDBConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/config/source/PaymentDBConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/config/source/ReservationDBConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/config/source/UserDBConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/config/source/VenueDBConfig.java
  batch/src/main/resources/application-source-db.yml
  batch/src/main/resources/application.yml
Labels: chore

#289 [ET-169] chore(alarm) : 모듈 생성
  alarm/.gitattributes
  alarm/.gitignore
  alarm/build.gradle
  alarm/gradle/wrapper/gradle-wrapper.jar
  alarm/gradle/wrapper/gradle-wrapper.properties
  alarm/gradlew
  alarm/gradlew.bat
  alarm/settings.gradle
  alarm/src/main/java/com/earlybird/ticket/alarm/AlarmApplication.java
  alarm/src/main/resources/application.yml
  settings.gradle
Labels: chore

#287 [ET-168] refactor(reservation) : 예약 생성 Consumer 추가 및 불필요한 dto 내 passp…
  common/src/main/java/com/earlybird/ticket/common/entity/constant/Code.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/dto/response/SeatPreemptFailPayload.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/dto/response/SeatPreemptSuccessPayload.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/CreateReservationRequestHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/PreemptSeatFailPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/PreemptSeatSuccessPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/service/ReservationService.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/service/ReservationServiceImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/ConfirmCouponEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/ConfirmSeatEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/CreateReservationEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/PreemptSeatDltEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/PreemptSeatEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/ReservationFailEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/ReserveCouponEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/ReturnCouponEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/ReturnSeatEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/SuccessCouponEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/Reservation.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/ReservationSeat.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/constant/EventType.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/repository/ReservationSeatRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservationSeat/ReservationSeatRepositoryImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/presentation/ReservationExternalController.java
Labels: refactor

#290 [ET-170] feat(alarm) : 환경설정 및 기본 셋팅
  alarm/build.gradle
  alarm/settings.gradle
  alarm/src/main/java/com/earlybird/ticket/alarm/application/dispatcher/EventDispatcher.java
  alarm/src/main/java/com/earlybird/ticket/alarm/application/dispatcher/EventDispatcherImpl.java
  alarm/src/main/java/com/earlybird/ticket/alarm/application/event/EventHandler.java
  alarm/src/main/java/com/earlybird/ticket/alarm/common/config/CommonConfig.java
  alarm/src/main/java/com/earlybird/ticket/alarm/common/exception/CustomJsonProcessingException.java
  alarm/src/main/java/com/earlybird/ticket/alarm/common/exception/NonRecoverableReservationException.java
  alarm/src/main/java/com/earlybird/ticket/alarm/common/exception/RecoverableReservationException.java
  alarm/src/main/java/com/earlybird/ticket/alarm/common/util/EventPayloadConverter.java
  alarm/src/main/java/com/earlybird/ticket/alarm/domain/Event.java
  alarm/src/main/java/com/earlybird/ticket/alarm/domain/Outbox.java
  alarm/src/main/java/com/earlybird/ticket/alarm/domain/constant/EventType.java
  alarm/src/main/java/com/earlybird/ticket/alarm/domain/dto/request/CreateAlarmEvent.java
  alarm/src/main/java/com/earlybird/ticket/alarm/domain/repository/OutboxRepository.java
  alarm/src/main/java/com/earlybird/ticket/alarm/infrastructure/messaging/config/KafkaConfig.java
  alarm/src/main/java/com/earlybird/ticket/alarm/infrastructure/messaging/config/KafkaConsumerConfig.java
  alarm/src/main/java/com/earlybird/ticket/alarm/infrastructure/messaging/config/KafkaProducerConfig.java
  alarm/src/main/java/com/earlybird/ticket/alarm/infrastructure/messaging/consumer/ReservationKafkaEventListener.java
  alarm/src/main/java/com/earlybird/ticket/alarm/infrastructure/messaging/producer/KafkaProducerInterceptor.java
  alarm/src/main/java/com/earlybird/ticket/alarm/infrastructure/messaging/producer/KafkaProducerListener.java
  alarm/src/main/java/com/earlybird/ticket/alarm/infrastructure/messaging/producer/ReservationKafkaOutboxProducer.java
  alarm/src/main/java/com/earlybird/ticket/alarm/infrastructure/repository/outbox/OutboxJpaRepository.java
  alarm/src/main/java/com/earlybird/ticket/alarm/infrastructure/repository/outbox/OutboxRepositoryImpl.java
  alarm/src/main/resources/application.yml
Labels: enhancement

#292 Refactor(seat)/preempt seat
  common/src/main/java/com/earlybird/ticket/common/entity/constant/Code.java
  venue/src/main/java/com/earlybird/ticket/venue/application/dto/request/SeatPreemptCommand.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/ReservationCreateFailPayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/SeatPreemptPayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/response/ReservationCreateEvent.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/response/SeatPreemptFailEvent.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/ReservationCreateFailEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatHandlerService.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatHandlerServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatPreemptEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatService.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/common/event/EventType.java
  venue/src/main/java/com/earlybird/ticket/venue/common/exception/RedisException.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/entity/constant/ConcertStatus.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/redis/RedisConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/messaging/SeatKafkaEventListener.java
  venue/src/main/java/com/earlybird/ticket/venue/presentation/controller/SeatController.java
  venue/src/main/java/com/earlybird/ticket/venue/presentation/dto/request/SeatPreemptRequest.java
  venue/src/main/resources/application.yml
Labels: refactor

#295 [ET-179] feat(batch) : payment outbox 수집
  batch/src/main/java/com/earlybird/ticket/batch/config/sink/SinkDBConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/domain/entity/Outbox.java
  batch/src/main/java/com/earlybird/ticket/batch/domain/repository/OutboxRepository.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/config/jdbc/OutboxCollectBatchConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/dto/response/OutboxMessage.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/repository/OutboxJpaRepository.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/repository/OutboxRepositoryImpl.java
  batch/src/main/java/com/earlybird/ticket/batch/presentation/BatchJobEndpoint.java
  batch/src/main/resources/application.yml
Labels: enhancement

#296 Feat(seat)/warm up seat instance
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/domain/repository/SeatRepository.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/redis/RedisConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/SeatQueryRepository.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/SeatQueryRepositoryImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/repository/SeatRepositoryImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/presentation/controller/SeatController.java
  venue/src/main/resources/application.yml
Labels: enhancement

#299 [ET-163] feat: micro service별 dockerfile 생성 #297
  admin/Dockerfile
  alarm/Dockerfile
  auth/Dockerfile
  batch/Dockerfile
  concert/Dockerfile
  coupon/Dockerfile
  gateway/Dockerfile
  payment/Dockerfile
  reservation/Dockerfile
  server/Dockerfile
  user/Dockerfile
  venue/Dockerfile
Labels: enhancement

#300 [ET-180] feat: micro service별 dockerfile 생성 #298
  admin/build.gradle
  admin/gradlew
  admin/gradlew.bat
  batch/gradle/wrapper/gradle-wrapper.jar
  batch/gradle/wrapper/gradle-wrapper.properties
  concert/build.gradle
  concert/gradlew
  concert/gradlew.bat
  coupon/build.gradle
  coupon/gradlew
  coupon/gradlew.bat
  docker-compose.db.yml
  docker-compose.kafka.yml
  docker-compose.yml
Labels: enhancement

#305 Refactor(seat)/refactor seat list
  venue/src/main/java/com/earlybird/ticket/venue/application/dto/response/SeatListQuery.java
  venue/src/main/java/com/earlybird/ticket/venue/application/dto/response/SectionListQuery.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatHandlerServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/common/exception/RedisException.java
  venue/src/main/java/com/earlybird/ticket/venue/common/util/EventConverter.java
  venue/src/main/java/com/earlybird/ticket/venue/common/util/RedisKeyScanner.java
Labels: refactor

#303 [ET-183] Outbox 마이그레이션 작업 추가
  batch/src/main/java/com/earlybird/ticket/batch/domain/entity/Outbox.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/config/jdbc/OutboxCollectBatchConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/config/jdbc/OutboxItemSqlParameterSourceProvider.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/dto/response/OutboxMessage.java
  batch/src/main/resources/application.yml
Labels: enhancement

#307 Refactor(seat)/refactor inquiry method
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/common/dto/RedisReadResult.java
  venue/src/main/java/com/earlybird/ticket/venue/common/util/AbstractRedisHashReader.java
  venue/src/main/java/com/earlybird/ticket/venue/common/util/RedisKeyFactory.java
  venue/src/main/java/com/earlybird/ticket/venue/common/util/RedisSeatListReader.java
  venue/src/main/java/com/earlybird/ticket/venue/common/util/RedisSectionListReader.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/redis/RedisConfig.java
Labels: refactor

#311 Refactor(seat)/refactor check seat
  venue/src/main/java/com/earlybird/ticket/venue/application/dto/request/ProcessSeatCheckCommand.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/redis/RedisConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/presentation/dto/request/ProcessSeatCheckRequest.java
Labels: refactor

#317 Refactor(seat)/refactor confirm return seat
  venue/build.gradle
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/ReservationCreateFailPayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/SeatConfirmPayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/request/SeatReturnPayload.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dto/response/ReservationCreateEvent.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/ReservationCreateFailEventHandler.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatHandlerService.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatHandlerServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/common/event/EventType.java
  venue/src/main/java/com/earlybird/ticket/venue/common/exception/SeatPreemptionMismatchException.java
  venue/src/main/java/com/earlybird/ticket/venue/common/exception/SeatReturnFailException.java
  venue/src/main/java/com/earlybird/ticket/venue/common/util/AbstractRedisHashReader.java
  venue/src/main/java/com/earlybird/ticket/venue/common/util/EventConverter.java
  venue/src/main/java/com/earlybird/ticket/venue/common/util/RedisKeyFactory.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/redis/RedisConfig.java
Labels: refactor

#319 [ET-195] 배치 모듈 분산 트랜잭션 적용
  batch/build.gradle
  batch/src/main/java/com/earlybird/ticket/batch/config/sink/JtaTransactionManagerConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/config/sink/SinkDBConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/config/source/AdminDBConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/config/source/ConcertDBConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/config/source/CouponDBConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/config/source/PaymentDBConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/config/source/ReservationDBConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/config/source/UserDBConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/config/source/VenueDBConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/config/jdbc/AdminStepConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/config/jdbc/ConcertStepConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/config/jdbc/CouponStepConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/config/jdbc/OutboxCollectBatchConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/config/jdbc/PaymentStepConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/config/jdbc/ReservationStepConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/config/jdbc/VenueStepConfig.java
  batch/src/main/resources/application-source-db.yml
  batch/src/main/resources/application.yml
Labels: enhancement, refactor

#321 Feat(seat)/preempt vip
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatService.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/config/redis/RedisConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/presentation/controller/SeatController.java
Labels: enhancement

#322 [ET-201] refactoring(common) : traceId 적용 및 로그백,aop 수정
  common/build.gradle
  common/src/main/java/com/earlybird/ticket/common/aop/CachingMdcFilter.java
  common/src/main/java/com/earlybird/ticket/common/aop/LoggingAop.java
  common/src/main/java/com/earlybird/ticket/common/aop/LoggingTracer.java
  common/src/main/java/com/earlybird/ticket/common/aop/SchedulerConfig.java
  common/src/main/java/com/earlybird/ticket/common/aop/WebLogConfig.java
  common/src/main/java/com/earlybird/ticket/common/util/MDCTraceUtils.java
  common/src/main/resources/logback-spring.xml
Labels: refactor

#324 [ET-202] feat(coupon): coupon kafka config 추가 #323
  coupon/src/main/java/com/earlybird/ticket/coupon/infrastructure/config/KafkaConsumerConfig.java
  coupon/src/main/java/com/earlybird/ticket/coupon/infrastructure/config/KafkaProducerConfig.java
  coupon/src/main/java/com/earlybird/ticket/coupon/infrastructure/event/OutboxPublisher.java
  coupon/src/main/java/com/earlybird/ticket/coupon/infrastructure/message/CouponKafkaEventListener.java
Labels: enhancement

#326 [ET-203] refactoring(reservation) : 예약 조회 및 로그 설정
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ConfirmSeatSuccessPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ReserveCouponPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/ReturnSeatSuccessPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/TestPayloadHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/service/ReservationServiceImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/repository/ReservationRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/messaging/consumer/ReservationKafkaEventListener.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/messaging/producer/KafkaProducerInterceptor.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/messaging/producer/KafkaProducerListener.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/messaging/producer/ReservationKafkaOutboxProducer.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservation/ReservationJpaRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservation/ReservationRepositoryImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/presentation/ReservationExternalController.java
  reservation/src/main/resources/application.yml
Labels: refactor

#328 Feat(batch)/gather each service outbox
  batch/build.gradle
  batch/src/main/java/com/earlybird/ticket/batch/config/sink/FlywayConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/config/sink/SinkDBConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/config/jdbc/AdminStepConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/config/jdbc/ConcertStepConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/config/jdbc/CouponStepConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/config/jdbc/PaymentStepConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/config/jdbc/ReservationStepConfig.java
  batch/src/main/java/com/earlybird/ticket/batch/infrastructure/config/jdbc/VenueStepConfig.java
  batch/src/main/resources/application.yml
  batch/src/main/resources/db/migration/V1__init.sql
Labels: enhancement

#329 Refactor(reservation)/reservation create event
  reservation/src/main/java/com/earlybird/ticket/reservation/application/dispatcher/EventFactory.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/handler/CreateReservationRequestHandler.java
  reservation/src/main/java/com/earlybird/ticket/reservation/application/service/ReservationServiceImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/CreateReservationPayload.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/dto/request/ReservationFailEvent.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/Reservation.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/entity/constant/EventType.java
  reservation/src/main/java/com/earlybird/ticket/reservation/domain/repository/ReservationRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/messaging/consumer/ReservationKafkaEventListener.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservation/ReservationJpaRepository.java
  reservation/src/main/java/com/earlybird/ticket/reservation/infrastructure/repository/reservation/ReservationRepositoryImpl.java
  reservation/src/main/java/com/earlybird/ticket/reservation/presentation/ReservationExternalController.java
  reservation/src/main/resources/logback-spring.xml
Labels: bug, refactor

#330 [ET-207] chore(ELK) : 모니터링 yml파일 설정
  docker-compose.elk.yml
  filebeat.yml
  logstash.conf
Labels: chore

#333 [ET-196] refactor(seat) : 좌석 선점 기능 공통 로직 메서드 추출 (#332)
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatServiceImpl.java
Labels: refactor

#336 Refactor(seat)/refactor infra package
  venue/src/main/java/com/earlybird/ticket/venue/application/event/dispatcher/EventDispatcherImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/application/event/handler/SeatHandlerServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/application/service/SeatServiceImpl.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/kafka/config/KafkaConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/kafka/config/KafkaConsumerConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/kafka/config/KafkaProducerConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/kafka/config/KafkaProducerInterceptor.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/kafka/config/KafkaProducerListener.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/kafka/messaging/EventDispatcher.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/kafka/messaging/SeatKafkaEventListener.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/kafka/messaging/VenueKafkaEventListener.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/kafka/messaging/VenueKafkaOutboxProducer.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/redis/config/RedisConfig.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/redis/util/AbstractRedisHashReader.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/redis/util/RedisKeyFactory.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/redis/util/RedisKeyScanner.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/redis/util/RedisSeatListReader.java
  venue/src/main/java/com/earlybird/ticket/venue/infrastructure/redis/util/RedisSectionListReader.java
Labels: refactor

#338 [ET-209] chore(prometheous) : 모니터링 yml파일, gradle 설정, 경로 권한 추가
  admin/src/main/resources/application.yml
  auth/build.gradle
  auth/src/main/java/com/earlybird/ticket/auth/common/config/SecurityConfig.java
  auth/src/main/resources/application.yml
  concert/src/main/resources/application.yml
  coupon/src/main/resources/application.yml
  docker-compose.monitoring.yml
  gateway/build.gradle
  gateway/src/main/java/com/earlybird/ticket/gateway/infrastructure/config/SecurityWebConfig.java
  gateway/src/main/resources/application.yml
  loki-local-config.yaml
  payment/src/main/resources/application.yml
  prometheus.yml
  promtail-config.yml
  server/build.gradle
  server/src/main/resources/application.yml
  user/build.gradle
  user/src/main/resources/application.yml
  venue/src/main/resources/application.yml
Labels: chore

#340 [ET-210] feat: service 내 application.yml eureka 일괄 수정 #339
  admin/src/main/resources/application.yml
  alarm/src/main/resources/application.yml
  auth/src/main/resources/application.yml
  concert/src/main/resources/application.yml
  coupon/src/main/resources/application.yml
  gateway/src/main/resources/application.yml
  payment/src/main/resources/application.yml
  reservation/src/main/resources/application.yml
  server/src/main/resources/application.yml
  user/src/main/resources/application.yml
  venue/src/main/resources/application.yml
Labels: enhancement
